### ISSUE TITLE
TikTokApi.php

### ISSUE THREAD

**Issue by chefuz** [truongbo17/tiktok-api#1]
Fatal error: Uncaught Error: Class "TruongBo\TikTokApi\TikTokApi" not found

**Comment by Nithin-Lilac2024** [comment]
is there any possible way to increase the response count from 50 comments to infinte

**Comment by truongbo17** [comment]
> is there any possible way to increase the response count from 50 comments to infinte

Not possible because this is a 3rd party api. Even if i have the api directly from tiktok, i cant get all comments at once, no one allows that to happen.N

**Comment by truongbo17** [comment]
> Fatal error: Uncaught Error: Class "TruongBo\TikTokApi\TikTokApi" not found

show me your code, or try `php artisan optimize:clear` after run composer install

**Comment by truongbo17** [comment]
@chefuz if the problem persists, please create a new issue
